name: Build Windows EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Build
        run: |
          pip install pandas pyautogui pyinstaller
          pyinstaller --onefile --windowed uso-e-consumo.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: meu-executavel
          path: dist/*.exe
